### ISSUE TITLE
Don't assume that bridge have layer=1

### ISSUE THREAD

**Issue by freemeng** [keepright/keepright#51]
Don't assume that bridge have layer=1 and tunnel hava layer=-1.According to layer's wiki page,elements without layer tag have layer=0.It will lead to keepright think bridge without layer cross bridge having layer=1 without common node is an  error。

**Comment by mueschel** [comment]
The wiki entry on bridges states "For data users, note that about 25% of the bridges is missing a layer tag, in those cases, it's best to assume layer=1."
Both guesses about a missing layer tag (either 0 or 1) will lead to one or another wrong error message. To me it seems that the layer=1 assumption has less false positives. Maybe one should think about flagging all bridges without a layer tag as a warning.

**Comment by RicoZ-OSM** [comment]
It is wrong to assume default layer=1 for bridges  - and the same for tunnels. The proposal to treat bridges/tunnels with missing layer as layer=+/1 was turned down hands down in voting - http://wiki.openstreetmap.org/wiki/Proposed_features/default_layer_for_bridge_and_tunnel - and the same arguments that were presented in the discussion are also valid here.

It also leads to many wrong messages like this two - http://keepright.ipax.at/report_map.php?schema=98&error=37251136

The right way to do it for data consumers is http://wiki.openstreetmap.org/wiki/Key:layer#Data_consumers and I have fixed key:bridge now.

If anything than keepright could display a warning about a missing layer but I suspect you don't want a map with that many warnings.

**Comment by RicoZ-OSM** [comment]
Ping - do you realize that Keepright displays hundreds of thousands of completely wrong messages for perfectly valid crossings because of this?

**Comment by mueschel** [comment]
There are definitely not "hundreds of thousands" wrong messages because of that. In fact, there would be many times more errors if I were to assume bridges and tunnels without layer tag to be on layer 0.  
As you mentioned the proposal, please read the comments carefully. Most of them are, that it should be up to the data consumers to decide on default layers. Keepright is a data consumer and therefore free to decide how to treat the case of missing information. Sorry to say that, but his is definitely something I can not change.

**Comment by RicoZ-OSM** [comment]
Was there any movement in this?

The suggested fix - use layer=0.5 for bridges that don't have an explicit layer (and resp for tunnels) should not be terribly hard to implement and would eliminate 99% of the false positives.
