### ISSUE TITLE
Mispelled tag bug - don't use '0' to mean 'some number'

### ISSUE THREAD

**Issue by artischocke** [keepright/keepright#69]
I just ran a few instances of this in Collier County, Florida. The error reads:

> This way is tagged 'destination:ref=CR 846' where "CR 0" looks like "SR 0"

Specifically, the 0 confuses me, since it's not in "CR 846" at all. Secondly, CR is a valid prefix, denoting a [county road](https://en.wikipedia.org/wiki/County_highway). As far as I know, "SR" is discouraged as a prefix for state routes; [the state abbreviation is preferred](http://wiki.openstreetmap.org/wiki/United_States_roads_tagging#State_Highways), e.g. `ref="FL 29"` for Florida State Route 29 (SR 29).

Here's one of the occurrences: http://keepright.at/report_map.php?schema=68&error=88619598 but as many of the exits on I-75 that lead to county roads use destination:ref=CR*, there are many instances of the error in the area

**Comment by mueschel** [comment]
This check is based on pure statistics, if one tag appears much more often than another very similar one, it generates an error flag. 
The '0' appears, because the check ignores digits, i.e. "CR 846" and "CR 888" are not treated as different tags.
"ref=*" was already excluded from the check on keepright.at because checking doesn't make much sense for the values of 'ref'. The latest version of the code (unfortunately not yet available on keepright.at) excludes destination:ref as well, see:
http://osm.mueschelsoft.de/keepright/report_map.php?zoom=17&lat=26.27709&lon=-81.74272&layers=B0T&ch=0%2C220&show_ign=1&show_tmpign=1

**Comment by artischocke** [comment]
Thanks for the super fast response! :)

**Comment by artischocke** [comment]
Ok, just saw a different error with the "0", and perhaps the fact that digits are not being considered could be represented a different way so as to be less confusing. The error reads

> This node is tagged 'rating=112 MVA' where "0 MVA" looks like "0 kVA"

Not sure if using a * (asterisk) to mean "anything before the following text", as in a regular expression would be clearer, or confusing to non-programmers. Perhaps an ellipsis "…"?

**Comment by mueschel** [comment]
good point, I will change that.

**Comment by mueschel** [comment]
For now I changed it to "#" - I hope this is not too confusing. 
Changes will appear on http://osm.mueschelsoft.de/keepright/ during the next days.
